# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# See that the sum of the even-valued terms given the first 10 terms is 44.

sum = 0

fibLast = 1
fibCurr = 2

while fibCurr < 90:
    fibTemp = fibCurr
    if fibCurr % 2 == 0:
        sum += fibCurr
    fibCurr = fibCurr + fibLast
    fibLast = fibTemp

print(sum)